"""Tests for the GPAW unfolding readers (story 017).

Fixtures: tests/data/gpaw/*.gpw, generated by the sibling repo's
examples/gpaw_si/generate_fixtures.py (gpaw >= 26, PBE, Gamma-centered
grids, symmetry off, mode='all' restarts).

Sealed:

* LCAO reader: table shapes over the Gamma-centered 4x4x4 grid, exact
  inverse-transform roundtrip against ``get_lcao_hamiltonian`` at every
  stored k-point, Gamma eigenvalues against ``calc.get_eigenvalues``,
  and convention-2 phases (H(k) = sum_T H[T] e^{+2 pi i k.T}).
* Planewave reader: GpawPWData shapes, coefficient normalization, exact
  integer G vectors inside the cutoff sphere, and Gamma eigenvalues
  against ``calc.get_eigenvalues``.
"""

import os

import numpy as np
import pytest

DATA = os.path.join(os.path.dirname(__file__), "data", "gpaw")
BOHR = 0.529177210903  # Angstrom


@pytest.fixture(scope="module")
def prim_calc_and_model():
    pytest.importorskip("gpaw")
    from gpaw import restart

    from HamiltonIO.gpaw import GpawLcaoModel

    path = os.path.join(DATA, "si_prim_lcao.gpw")
    if not os.path.exists(path):
        pytest.skip("fixture missing: si_prim_lcao.gpw")
    atoms, calc = restart(path, txt=None)
    model = GpawLcaoModel.from_file(path)
    return atoms, calc, model


@pytest.fixture(scope="module")
def pw_data():
    pytest.importorskip("gpaw")
    from gpaw import restart

    from HamiltonIO.gpaw import GpawPWParser

    path = os.path.join(DATA, "si8_pw.gpw")
    if not os.path.exists(path):
        pytest.skip("fixture missing: si8_pw.gpw")
    atoms, calc = restart(path, txt=None)
    return atoms, calc, GpawPWParser(path).read()


def test_lcao_table_shapes(prim_calc_and_model):
    _, calc, model = prim_calc_and_model
    assert len(model.atoms) == 2
    assert model.kgrid == (4, 4, 4)
    assert next(iter(model.SR.values())).shape == (8, 8)
    # Nyquist shells are paired at +/-N/2 so the real-space tables
    # remain Hermitian even between the sampled k-points.
    ts = np.array(sorted(model.SR))
    assert np.all(ts.max(axis=0) == -ts.min(axis=0))
    viol = 0.0
    for T, block in model.SR.items():
        partner = model.SR.get(tuple(-np.array(T)))
        if partner is not None:
            viol = max(viol, np.abs(block - partner.conj().T).max())
        viol = max(
            viol,
            np.abs(model.HR[T] - model.HR[T].conj().T).max()
            if tuple(-np.array(T)) == T
            else viol,
        )
    assert viol < 1e-12


def test_lcao_roundtrip_on_grid(prim_calc_and_model):
    """Model matrices at stored grid k reproduce get_lcao_hamiltonian."""
    from gpaw.lcao.tools import get_lcao_hamiltonian

    _, calc, model = prim_calc_and_model
    H_skMM, S_kMM = get_lcao_hamiltonian(calc)
    ibzk = calc.get_ibz_k_points()
    for j, k in enumerate(ibzk):
        H, S = model.hs_and_eigen(k)
        err = max(np.abs(H - H_skMM[0][j]).max(), np.abs(S - S_kMM[j]).max())
        assert err < 1e-8


def test_lcao_gamma_eigenvalues_vs_calc(prim_calc_and_model):
    from scipy.linalg import eigh

    _, calc, model = prim_calc_and_model
    ibzk = calc.get_ibz_k_points()
    igamma = int(np.linalg.norm(ibzk, axis=1).argmin())
    assert np.linalg.norm(ibzk[igamma]) < 1e-10
    ref = np.sort(calc.get_eigenvalues(kpt=igamma))
    h, s = model.hs_and_eigen([0.0, 0.0, 0.0])
    got = np.sort(eigh(h, s, eigvals_only=True))
    assert np.abs(got - ref).max() < 1e-6


def test_lcao_convention2_phases(prim_calc_and_model):
    """H(-k) = conj(H(k)) in the convention-2 tables (time reversal)."""
    _, _, model = prim_calc_and_model
    k = np.array([0.11, -0.23, 0.05])
    h1, s1 = model.hs_and_eigen(k)
    h2, s2 = model.hs_and_eigen(-k)
    assert np.abs(h1 - h2.conj()).max() < 1e-8
    assert np.abs(s1 - s2.conj()).max() < 1e-8


def test_pw_data_shapes(pw_data):
    _, calc, data = pw_data
    nk = len(data.kpoints)
    assert data.kpoints.shape == (nk, 3)
    assert data.kpoints_cart.shape == (nk, 3)
    assert data.eigenvalues.shape == (nk, data.nbands)
    assert len(data.coefficients) == len(data.gvecs) == nk
    assert data.nspin == 1
    # every band normalized to sum |c|^2 = 1
    for c in data.coefficients:
        norms = np.einsum("ng,ng->n", c, c.conj()).real
        np.testing.assert_allclose(norms, 1.0, atol=1e-10)
    # cartesian k points match the fractional ones through the cell
    bcart = 2 * np.pi * np.linalg.inv(data.cell).T
    np.testing.assert_allclose(data.kpoints_cart, data.kpoints @ bcart, atol=1e-10)


def test_pw_gvecs_inside_cutoff(pw_data):
    """Integer G vectors reconstruct the stored G+k and obey the cutoff."""

    atoms, calc, data = pw_data
    ecut_ha = 340.0 / 27.211386245988
    cell_bohr = np.asarray(atoms.cell) / BOHR
    bmat = 2 * np.pi * np.linalg.inv(cell_bohr).T
    for ik, (g, kf, c) in enumerate(zip(data.gvecs, data.kpoints, data.coefficients)):
        gk = (g + kf) @ bmat
        kin = 0.5 * (gk**2).sum(axis=1)
        assert kin.max() <= ecut_ha * (1 + 1e-6)
        assert g.shape == (c.shape[-1], 3)
        assert np.abs(g - np.round(g)).max() == 0


def test_pw_gamma_eigenvalues_vs_calc(pw_data):
    _, calc, data = pw_data
    igamma = int(np.linalg.norm(data.kpoints, axis=1).argmin())
    assert np.linalg.norm(data.kpoints[igamma]) < 1e-10
    ref = np.sort(calc.get_eigenvalues(kpt=igamma))
    got = np.sort(data.eigenvalues[igamma])
    assert np.abs(got - ref).max() < 1e-6
